feat: add preserve value to field API
TanStack/form pull request #444
Opened 2023-09-07 19:38 UTC by vikaskumar89

Issue: https://github.com/TanStack/form/issues/417

This PR adds the preserve value property to Field API 
Adds deleteField method to form

2023-09-07 22:11 UTC, crutchcorn requested changes
This overall looks great! Let's see if we can add tests to:

- Core/FieldAPI
- React/FieldAPI

Before merging :)

2023-10-24 06:25 UTC, vikaskumar89 commented
@crutchcorn please see if this can be merged.

2023-10-30 05:48 UTC, crutchcorn approved these changes

2023-10-30 06:01 UTC, merged

2023-10-30 06:02 UTC, crutchcorn commented
@vikaskumar89 this was an awesome contribution. Thank you so much for building it and for your immense patience - I'll make sure your next contribution is expedited much faster than this one was. 😅