feat: solid.js form
TanStack/form pull request #471
Opened 2023-10-03 05:29 UTC by aadito123

The Solid.js port of the form/core

Made all the options parameters functions to match how they are done in TanStack/query v5, that way reactive parameters don't require getters.

For Field, I had to do some finagling to register changes in the Field.store into Solid's reactivity. It makes the reactivity far less fine-grained than it could be since any change in the store would cause any effect subscribing to any unrelated field would still run. I was thinking of using a Proxy but the Field.store has many methods on them and I am unsure how to work on those.

2023-10-03 05:32 UTC, crutchcorn commented
This is incredible! Thank you!

Are you up for a chat via Discord voice call by chance? Would love to walk through what potential next steps are and what edges of the code you'd like to look through! 😊

2023-10-03 05:48 UTC, aadito123 commented
Sure! What's your username?

2023-10-09 09:47 UTC, crutchcorn requested changes

2023-10-09 09:47 UTC, crutchcorn commented on packages/solid-form/src/createField.tsx
> +}
Let's see if we can't replace this with our `@tanstack/store` implementation from @wobsoriano (speaking of, if you @wobsoriano could review this PR as another Solid pro, that would be rad):

https://github.com/TanStack/store/pull/25

2023-10-09 09:47 UTC, crutchcorn commented on packages/solid-form/src/createForm.tsx
> +  )
Let's split this into two distinct items for code readability and maybe even remove the `isSubmitting` check

2023-10-30 06:07 UTC, crutchcorn commented
I'm taking over this here PR 🏴‍☠️🦜 

Namely, I want to make sure we have:

- Updates to docs (even if they're just `todo`s for now)
- Examples
- Adding to our deployment strategy so the new package gets published

And I feel guilty with how long this PR has been in the oven (my fault 100%). Gonna try to take your awesome effort and push it past the finish line tonight

2023-10-30 07:17 UTC, merged