fix: should run validation on submit and clear error if a valid  value is entered
TanStack/form pull request #520
Opened 2023-11-10 15:31 UTC by vikaskumar89

This PR fixes issue https://github.com/TanStack/form/issues/490 and https://github.com/TanStack/form/issues/486.

## What is changed
- on form submit, onChange/onBlur validation is run if present. If the validation fails, form is disabled
- clear the onSubmit error If a valid value is entered.

2023-12-01 16:44 UTC, vikaskumar89 commented
> Is there anything currently preventing this from being merged?

Maintainer is very slow. cc. @tannerlinsley

2023-12-03 09:49 UTC, eastack commented
I'm not sure when the maintainer will merge this, but is there any other way we can work around these issues temporarily?

2023-12-03 09:57 UTC, crutchcorn commented
Hey all, maintainer here.

@vikaskumar89 I will need you to please start being patient with me. On top of TanStack Form not being 1.x yet (in which case bug fixes will be merged much faster), I also work on various other OSS projects, am trying to finish writing a book, am oftentimes busy with personal issues, and to top it off am not really getting paid for this work (minus a few generous donors albeit for relatively little amounts).

Please do not tag Tanner directly, and know that I will eventually come back to things here.

There is a reason I am "slow" :)

That all said, I will be reviewing this shortly.

2023-12-03 10:08 UTC, crutchcorn commented on packages/form-core/src/FieldApi.ts
> +          : onBlur
This is not the correct backup to `cause === "submit" && !onChange`

Instead, we need to run both `onChange` **and** `onBlur`.

I'll take over this PR to make the appropriate changes.

2023-12-03 10:08 UTC, crutchcorn requested changes

2023-12-03 10:08 UTC, crutchcorn commented on packages/form-core/src/FieldApi.ts
> +          : onBlur
This is not the correct backup to `cause === "submit" && !onChange`

Instead, we need to run both `onChange` **and** `onBlur`.

I'll take over this PR to make the appropriate changes.

2023-12-03 10:31 UTC, crutchcorn approved these changes
Issues with implementation have now been resolved.

In addition, I've added `<Field onSubmit={z.string().min(1)}/>` functionality, which was missing previously.

I also added more tests than before.

2023-12-03 10:37 UTC, merged