docs(next-usage): usage of serveractions with next
TanStack/form pull request #566
Opened 2024-01-10 12:32 UTC by enyelsequeira

# Changelog

- Usage of `NextJs` with App router and using server actions
- @crutchcorn  as discussed on discord here is the usage of `form` with server actions, let me know if updates are needed

Thank you!

2024-01-11 19:25 UTC, crutchcorn requested changes
Minor changes, then we can merge :)

2024-01-11 19:25 UTC, crutchcorn commented on docs/framework/react/guides/next-js.md
> +- lets understand what is happening here, we need to use the `useFormState` hooks which give us the current state and the action. The way the hooks work is we have to give it an `action` in our case
Capitalize `lets` :)

2024-01-11 19:25 UTC, crutchcorn commented on docs/framework/react/guides/next-js.md
> +- the `formFactory.useForm` takes a few properties that we can pass to it as an object the one we are using here is transform and we are using another hook that `@tanstack/react-form` provides which
Let's capitalize "the" here

2024-01-11 19:25 UTC, crutchcorn commented on docs/framework/react/guides/next-js.md
> +TanStack Form is compatible with React out of the box, supporting `SSR` and being framework-agnostic. However, specific configurations are necessary according to your chosen framework.
Let's add a link before the start of the content linking out to this blog series I wrote for the topic:

https://unicorn-utterances.com/collections/react-beyond-the-render

> Before reading this guide, it's suggested you understand how React Server Components and React Server Actions work. [Check out this blog series for more information.](https://unicorn-utterances.com/collections/react-beyond-the-render)

2024-01-12 11:57 UTC, enyelsequeira commented on docs/config.json
> +              "label": "Next JS",
Done

2024-01-12 12:07 UTC, enyelsequeira commented
hey @crutchcorn  changes you requested have been made and needed to change some files names to do the routing corrected

Thank you

2024-01-12 18:04 UTC, crutchcorn approved these changes

2024-01-12 18:05 UTC, merged