Add Arktype Validator
TanStack/form pull request #912
Opened 2024-08-18 14:45 UTC by Makisuo

2024-09-12 06:35 UTC, Pascalmh requested changes

2024-09-12 06:35 UTC, Pascalmh commented on examples/react/arktype/index.html
> +    <title>TanStack Form React Valibot Example App</title>
```suggestion
    <title>TanStack Form React Arktype Example App</title>
```

2024-09-12 06:35 UTC, Pascalmh commented on examples/react/arktype/src/index.tsx
> +      <h1>Valibot Form Example</h1>
```suggestion
      <h1>Arktype Form Example</h1>
```

2024-09-12 06:35 UTC, Pascalmh commented on examples/react/arktype/package.json
> +    "valibot": "^0.37.0"
The `"valibot"` dependency should not be needed here

2024-11-16 21:19 UTC, Balastrong commented
Thank you everyone for the effort here!
The bad news is that I'm closing this PR, the good news is that after #1020 lands, arktype will be natively supported as it implements Standard Schema 🙌

2024-11-16 21:19 UTC, closed without merging